spring:
  application:
    name: graphQL
  datasource:
    url: jdbc:mysql://localhost:3306/GRAPH_QL?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis
